### ISSUE TITLE
Improve documentation for usage with Docker Compose

### ISSUE THREAD

**Issue by kmturley** [carlossg/docker-maven#158]
In the current documentation it explains usage with Docker:
`docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn verify`

Developers often use [Docker Compose](https://docs.docker.com/compose/) to save configurations as yml files, and handle multiple Docker images at the same time. 

It would be useful to have an example `docker-compose.yml` file to speed up getting started. For example a Java/Maven project with a MySQL database:
```
version: '3.1'
services:

  backend:
    image: maven:3.6.3-jdk-8
    command: mvn clean spring-boot:run
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/mymaven:rw
    working_dir: /usr/src/mymaven

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
```

Having quick-start examples like this will increase adoption of the image, and save development time!
