### ISSUE TITLE
Dependencies are downloaded in every build 

### ISSUE THREAD

**Issue by slim-hmidi** [carlossg/docker-maven#162]
I created an image based on [openjdk-11-slim](https://github.com/carlossg/docker-maven/blob/master/openjdk-11-slim/Dockerfile) but I changed the maven to v 3.3.9.
Dockerfile:
```
FROM slimhs/maven-jdk-11:slim

ARG certFile=$certFilePath
ARG settingsFile=$settingsFilePath

COPY $certFile $JAVA_HOME/lib/security/
COPY settings.xml /usr/share/maven/ref/


#createtheworkdir
RUN mkdir -p /usr/src/ego-api
WORKDIR /usr/src/ego-ap

# copy the pom and src code to the container
COPY ./ /usr/src/ego-api
RUN mvn -o -B -f pom.xml -s /usr/share/maven/ref/settings.xml package

ENTRYPOINT ["java"]
CMD ["-jar", "./target/ego-1.0-SNAPSHOT.jar"]
```
docker-compose:
```
version: '3'
services:
  app:
    container_name: server
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      -  db
    working_dir: /usr/src/ego-api
    volumes:
      - "./src:/usr/src/ego-api"
      - "C:/Users/x199377/.m2:/root/.m2"

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=egoroot
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ego
```
When executing `docker-compose build --build-arg certFilePath=$JAVA_HOME\lib\security\jssecacerts --build-arg settingsFilePath=C:\Users\me\apache-maven-3.3.9\conf\settings.xml`, maven download the dependencies everytime.
I added `<localRepository>/usr/share/maven/ref/repository<localRepository>` and `<offline>true</offline>`, But it is the same thing.

As it mentioned on [Packaging a local repository with the image](https://github.com/carlossg/docker-maven#packaging-a-local-repository-with-the-image), at the build time everything under `/root/.m2` will be lost, and everything under `/usr/share/maven/ref/` will be copied to `/root/.m2`. That's why in every build maven download the dependencies.
Should I copy the depenencies after donwloading them the first time under `/usr/share/maven/ref` ? and if it's the solution, how can I download the new dependencies if the will exist in pom.Should I remove the image and build without cache?
Can you explain to me how can I fix the dependencies download with maven to not waiting every build some minutes to download everything whenever there is no dependency to download?
