### ISSUE TITLE
Missing image tag for temurin-21-jammy

### ISSUE THREAD

**Issue by zisuu** [carlossg/docker-maven#512]
Hello

I can not find any `3.8-eclipse-temurin-21-jammy` image tag -> https://hub.docker.com/_/maven/tags?name=3.8-eclipse-temurin-21 shows me only:
- [3.8-eclipse-temurin-21-alpine](https://hub.docker.com/layers/library/maven/3.8-eclipse-temurin-21-alpine/images/sha256-1c8e6af5df996fe35ab7cd2dff74edac8ceae2e00336d8748f0bcbdb81bba889?context=explore)
- [3.8-eclipse-temurin-21](https://hub.docker.com/layers/library/maven/3.8-eclipse-temurin-21/images/sha256-116cab0cbd7f9e9cda5289b1635907da4910969bde61a79920339ad41454582b?context=explore)

But there is a separate jammy tag for Maven 3.9:
- [3.9-eclipse-temurin-21-alpine](https://hub.docker.com/layers/library/maven/3.9-eclipse-temurin-21-alpine/images/sha256-98d452d2b41520d636c6737423b3e65f7827bf919ac4383b12d3f18ef182dea7?context=explore)
- [3.9-eclipse-temurin-21](https://hub.docker.com/layers/library/maven/3.9-eclipse-temurin-21/images/sha256-937adb4f5b9f004adf875ffec49ac1cf4ea80c5ab397689bb138252eb1154b31?context=explore)
- [3.9-eclipse-temurin-21-jammy](https://hub.docker.com/layers/library/maven/3.9-eclipse-temurin-21-jammy/images/sha256-e933dcf27cebeec926d45579248caf43826f6c260b126615ba9f13159364bbd8?context=explore)

Is that an unintentional tagging issue, or is there any reason not to ship the `3.8-eclipse-temurin-21-jammy` image tag? Could someone please add(build) the missing `3.8-eclipse-temurin-21-jammy` image tag?

Thanks a lot

**Comment by carlossg** [comment]
jammy was added in #437 after 3.9 was out, backporting to old maven versions would take too much time

**Comment by zisuu** [comment]
I see. Our problem is with the inconsistency of the tails as we template the tags in the image.

Do you see a way to add the distro version consistently into the image tail?

**Comment by carlossg** [comment]
what do you mean by tail?

**Comment by zisuu** [comment]
Let me explain why we need that tag.

We are building our devcontainer images with the following GitHub workflow matrix: 
```yml
---
name: Schedule / CD / Publish / Devcontainer

on:
  schedule:
    - cron: '30 3 * * SUN'
  workflow_dispatch:

env:
  image_name: docker.registry.example.com/devcontainer/maven

jobs:
  publish-devcontainers:
    name: "Build and Push Devcontainer"
    runs-on: self-hosted-runner
    strategy:
      fail-fast: false
      matrix:
        include:
          - maven_version: "3.8"
            java_version: '11'
            ubuntu_release: focal
          - maven_version: "3.8"
            java_version: '17'
            ubuntu_release: focal
          - maven_version: "3.9"
            java_version: '17'
            ubuntu_release: focal
          - maven_version: "3.9"
            java_version: '21'
            ubuntu_release: jammy
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build and Push Docker Image
        uses: org/actions-docker-build-push/.github/actions/docker-build-push@d121c18a9cf4b6182bc243be7163622668dc7c74 # v1.5.3
        with:
          docker_image: ${{ env.image_name }}
          docker_tags: ${{ matrix.maven_version }}-jdk-${{ matrix.java_version }}-${{ matrix.ubuntu_release}}
          build_options: |
            --build-arg MAVEN_VERSION=${{ matrix.maven_version }} \
            --build-arg JAVA_VERSION=${{ matrix.java_version }} \
            --build-arg UBUNTU_RELEASE=${{ matrix.ubuntu_release }}
          docker_username: ${{ secrets.DOCKER_USER }}
          docker_password: ${{ secrets.DOCKER_TOKEN }}
          docker_push: true
```
due to the fact that there is no tag `3.8-eclipse-temurin-21-jammy`, we cannot build a devcontainer for maven 3.8 with java 21 temurin on ubuntu jammy.
